//
// Created by leon on 29/06/2026.
//

#ifndef CONTROLADOR_DE_VIAGENS_CONTROLADORDETRANSITO_H
#define CONTROLADOR_DE_VIAGENS_CONTROLADORDETRANSITO_H


class ControladorDeTransito {
};


#endif //CONTROLADOR_DE_VIAGENS_CONTROLADORDETRANSITO_H
