//
// Created by leon on 29/06/2026.
//

#ifndef CONTROLADOR_DE_VIAGENS_PASSAGEIRO_H
#define CONTROLADOR_DE_VIAGENS_PASSAGEIRO_H


class Passageiro {
};


#endif //CONTROLADOR_DE_VIAGENS_PASSAGEIRO_H
